# Colors (Sugarplum)

[colors.bright]
black = '#111147'
blue = '#db7ddd'
cyan = '#cdab53'
green = '#53b397'
magenta = '#d0beee'
red = '#5ca8dc'
white = '#a175d4'
yellow = '#249a84'

[colors.cursor]
cursor = '#53b397'
text = '#53b397'

[colors.normal]
black = '#111147'
blue = '#db7ddd'
cyan = '#b5e4f4'
green = '#53b397'
magenta = '#d0beee'
red = '#5ca8dc'
white = '#a175d4'
yellow = '#249a84'

[colors.primary]
background = '#111147'
foreground = '#db7ddd'

[colors.selection]
background = '#5ca8dc'
text = '#d0beee'
