[colors]
background = '#111147'
foreground = '#db7ddd'
selection-background = '#5ca8dc'
selection-foreground = '#d0beee'
cursor = '#53b397'
black = '#111147'
red = '#5ca8dc'
green = '#53b397'
yellow = '#249a84'
blue = '#db7ddd'
magenta = '#d0beee'
cyan = '#b5e4f4'
white = '#a175d4'
light_black = '#111147'
light_red = '#5ca8dc'
light_green = '#53b397'
light_yellow = '#249a84'
light_blue = '#db7ddd'
light_magenta = '#d0beee'
light_cyan = '#cdab53'
light_white = '#a175d4'
